spring:
  application:
    name: com.atguigu.springcloud.config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2122446868/springcloud-alibaba.git
          search-paths:
            - com.atguigu.springcloud.config-file
          username: 2122446868@qq.com
          password: zcc19981218
          force-pull: true
      label: main
  rabbitmq:
    host: 192.168.31.128
    port: 5672
    username: guest
    password: guest

server:
  port: 3344


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
