spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2122446868/springcloud-alibaba.git
          search-paths:
            - config-file
          username: 2122446868@qq.com
          password: zcc19981218
          force-pull: true
      label: main

server:
  port: 3344


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/


