spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:

      label: master

server:
  port: 3344


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

