server:
  port: 83

spring:
  application:
    name: order



  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.128:8848








service-uri:
  nacos-use-service: http://payment-privider