server:
  port: 80

eureka:
  client:
    #    register-with-eureka: false
    register-with-eureka: true
    fetch-registry: true
    service-url:

      #      defaultZone: http://eureka7001.com:7001/eureka/
      defaultZone: http://localhost:7001/eureka/



logging:
  level:
    com.atguigu.springcloud.service: debug
feign:
  client:
    config:
      CLOUD-PROVIDER-HYSTRIX-PAYMENT:
        #连接超时时间，默认2s，设置单位为毫秒
        connectTimeout: 5000
        # 请求处理超时时间，默认5s，设置单位为毫秒。
        readTimeout: 5000
  hystrix:
    enabled: true


